require:
  - rubocop-rspec

AllCops:
  AutoCorrect: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true


Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/**/*
    - horizons.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - horizons.gemspec
